### ISSUE TITLE
境界値の日付をURLに直接入力するとエラーとなる。

### ISSUE THREAD

**Issue by hiramoto** [Kohei33/SeatBooking#9]
<img width="588" alt="2023-05-09_09h25_58" src="https://user-images.githubusercontent.com/4223173/236984609-72084091-ee7d-4a28-8747-adbba94462a0.png">
URLに西暦1年1月1日のbefore、西暦9999年12月31日のfutureを入力するとエラーが発生する。

**Comment by Kohei33** [comment]
デプロイ待ち

**Comment by Kohei33** [comment]
修正、デプロイ済み。
